version: "3.3"
services:
  go:
    tty: true
    build:
      context: ./go/src
      dockerfile: Dockerfile-dev
    volumes:
      - ./go/src:/var/apps
      - vscode:/root/.vscode-server
    restart: on-failure:5
  js:
    tty: true
    build:
      context: ./js
      dockerfile: Dockerfile-dev
    volumes:
      - node_modules:/var/apps/node_modules
      - ./js:/var/apps
      - vscode:/root/.vscode-server
    restart: on-failure:5

volumes:
  vscode:
  node_modules: